[Bus]
interface = "vcan0" # Can bus interface name. Use "can0" for real machine and "vcan0" for virtual machine.
baud_rate = 1000000

[[Node]]
    node_id = 1

[[Node]]
    node_id = 2

[[Node]]
    node_id = 3

[[Node]]
    node_id = 4

[[Node]]
    node_id = 5

[[Node]]
    node_id = 6

[[Node]]
    node_id = 7

[[Node]]
    node_id = 8

[[Node]]
    node_id = 9

[[Node]]
    node_id = 10

[[Node]]
    node_id = 11

[[Node]]
    node_id = 12

[[Node]]
    node_id = 13

[[Node]]
    node_id = 103

[[Node]]
    node_id = 104

[[Node]]
    node_id = 105

[[Node]]
    node_id = 106

[[Node]]
    node_id = 107

[[Node]]
    node_id = 108

[[Node]]
    node_id = 109

[[Node]]
    node_id = 110

[[Node]]
    node_id = 111

[[Node]]
    node_id = 112

[[Node]]
    node_id = 113