[General]
speed_factor = 10

[Bus]
interface = "vcan0" # Can bus interface name. Use "can0" for real machine and "vcan0" for virtual machine.

[[Node]]
    node_id = 1
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 2
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 3
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 4
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 5
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 6
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 7
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 8
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 9
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 10
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 11
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 12
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 13
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 103
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 104
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 105
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 106
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 107
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 108
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 109
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 110
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 111
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 112
    eds_file = "CPB3-1-2.eds"

[[Node]]
    node_id = 113
    eds_file = "CPB3-1-2.eds"